### ISSUE TITLE
Pattern: Create the Video player v1 functional specifications 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1066]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the Video player functional specs 

> so that I can:
so that I can properly code the Video player pattern

#### Additional information

 - [Pattern roadmap](https://github.ibm.com/webstandards/patterns/wiki/Pattern-roadmap) - _This URL may change as this linked wiki page may move to the public github_
 - This version should meet the Web Simplification MVP requirements
 - January 8 & 13 meeting notes and recording [Box Link](https://ibm.ent.box.com/notes/443167473382)
 - [Video Player v1.0.0 functional specs](https://ibm.ent.box.com/file/600045806474)

#### Acceptance criteria
 - [ ] Documented Featured Link functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Final changes from reviewing team members included in the functional specs, if applicable
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
 - [ ] Pattern roadmap wiki page is updated

**Comment by sethibm** [comment]
@jeffchew @photodow Here is the folder where the previous specs are located for "Image with caption" and "Video"

https://ibm.box.com/s/gpzvplwa5gyj1vvg1adl5apqmcnfa686

It's currently inside the Media component folder but may need to be moved, per file organization.  I placed it in here because my visual specs for this overall ontology are just for the Media component part, which shows all the related functional specs within it.
