### ISSUE TITLE
Abstract migration:  Feature card

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1084]
### user story
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Additional Information
 - Prod QA testing issue (#1213)

### Acceptance criteria
- [x] Upload the design spec file(s) to the [Layout patterns Abstract project](https://share.goabstract.com/374b8860-c315-4c4e-b229-fd1926ea8880?)
- [x] A collection in Abstract is created and the link to it is available
- [x] Associated Git stories have been updated with the new name and link
- [x] Update functional specs to point to the new Abstract hosted file
- [x] Add or update README Box note with a link pointing to the hosted file
- [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Abstract work is finished

**Comment by larahanlon2** [comment]
@photodow @wonilsuhibm @jeffchew @RobertaJHahn 

I had to create a new design spec file because the one in Box was out of date. The new design specs reflect the design QA bugs and comments we opened and discussed in the last sprint. I moved the old spec file (1.0.0) and PNGs to an archive folder in Box, if you need them.

@photodow can you take a look at func spec file and make sure it's pointing to the right design specs? Here's what's done:

- [x] New Sketch [design specs](https://ibm.box.com/s/aksuzr18ybbjxydgn16qmdesbfborrqh) added to Box
- [x] Abstract collection with updates specs can be viewed [here](https://share.goabstract.com/87e531fc-2820-4469-9969-a8d95f23533c?).
- [x] New [PNGs](https://ibm.box.com/s/0rybrt3us8gb66eiyhd72luw82e69uei) added to Box.
- [x] Old specs and PNGs have been moved to an [archive](https://ibm.box.com/s/xszl95g689eoijkbfbz34wyob5pbv5cs) folder.
- [x] [README](https://ibm.ent.box.com/notes/608134149695) has been added to Box with updated links.

**Comment by photodow** [comment]
@larahanlon2 thanks, updated the links
