### ISSUE TITLE
ExpressiveModal: 2x Grid alignment study

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#1091]
## Detailed description
So the 2x grid isn't expected to align perfectly with the items behind it. Basically we need to prepare especially the expandable modifier to allow the 2x grid to be used. That means proper gutter padding and spacing, and maybe test it out.

I think it's fair to look at the container/body of the modal as the grid container. We need to be careful with how to handle this because we don't want the `max-width` that comes with the original grid. Also one distinct difference is in the 2x grid at the `max` breakpoint the outer gutter adds an additional `8px` to its value. We want to ignore this and keep the same as `lg` was.

I don't know if we also want to bake in the row to this as well which mostly offsets the grid allowing the columns to line up correctly.

`sm`
![image](https://user-images.githubusercontent.com/3793636/72634250-c9c32400-391f-11ea-909e-3b3718427e4d.png)

`md`
![image](https://user-images.githubusercontent.com/3793636/72634180-b7e18100-391f-11ea-924f-9bb4b02f8bd4.png)

`lg`, `xlg`, `max`
![image](https://user-images.githubusercontent.com/3793636/72634133-91bbe100-391f-11ea-94d2-20167ba4d6be.png)

Reach out if you have any questions.

#### Additional information

- [LightboxMediaViewer Functional Specs](https://ibm.box.com/s/hq4eq9fdgb279o40h5ur5eonpo58359e)
- [ExpressiveModal Functional Specs](https://ibm.box.com/s/tcnaqe2k9c2kwue7t69nd2exhlws3ab8)
- [@carbon/grid](https://www.npmjs.com/package/@carbon/grid)

#### Acceptance criteria

- [ ] `sm` padding: 16px
- [ ] `md` `lg` `xlg` `max` padding: 32px
- [ ] `max` ignore grid's additional 8px
- [ ] ignore container's `max-width`
- [ ] 2x grid aligns inside modal
- [ ] standard breakpoints included `sm:4` `md:8` `lg:16` `xlg:16` `max:16`
- [ ] Leverage `@carbon/grid`

**Comment by wonilsuhibm** [comment]
Continuing with two models:
Model 1. Introduce a new inset 2x grid for modal
Model 2. Try to use the existing 2x grid

**Comment by wonilsuhibm** [comment]
Latest studies around the two models:
![component--expressive-modal--design--specs--max--12-cols](https://user-images.githubusercontent.com/30183447/76251416-518d2680-621d-11ea-871c-813a2e58c5bd.png)
![component--expressive-modal--design--specs--max--12-cols copy](https://user-images.githubusercontent.com/30183447/76251429-5520ad80-621d-11ea-92b8-1d53cc7f4465.png)
![component--expressive-modal--design--specs--max--12-cols copy 2](https://user-images.githubusercontent.com/30183447/76251439-57830780-621d-11ea-881b-b3e35f663298.png)

**Comment by wonilsuhibm** [comment]
@oliviaflory @larahanlon2 @JennySanchez @jacobottesen-dgc please take a look and add your thoughts.

@photodow is there any chance we can prototype these? How much work will it be?

**Comment by larahanlon2** [comment]
Thoughts:

- I think both `Model 1: inset 2x grid` and `Model 2: use the page level 2x grid` look great. The padding feels really comfortable in both. 
- In the 16-col version, I prefer the `Model 1: inset 2x grid` option because of the background overlay:

<img width="1008" alt="Screen Shot 2020-03-09 at 5 17 10 PM" src="https://user-images.githubusercontent.com/53093550/76258411-e3029580-6229-11ea-8691-6a26d24766bd.png">

- Keeping that semi-transparent overlay in the background makes it feel like a modal even at such a large size. Whereas the `Model 2: use the page level 2x grid` looks like a full-width page so maybe it's harder for users to see the close icon in the corner?

**Comment by larahanlon2** [comment]
Not really related to columns, but I wonder if the text block could be pinned to the bottom of the inside padding at this breakpoint? So that there is equal "border" padding the whole way around the modal?
<img width="1461" alt="Screen Shot 2020-03-09 at 5 07 46 PM" src="https://user-images.githubusercontent.com/53093550/76259034-227db180-622b-11ea-8b39-e992703c39a9.png">

**Comment by oliviaflory** [comment]
Agreed with Lara that the padding feels nice in both `Model 1` and `Model 2`

I think the background overlay in `Model 1` is helpful to orient the user and makes it more clear that it's an overlay. However it makes it a little harder to mock up properly in a sketch kit.. and on our existing grid templates.

`Model 2` is nice, but at the 16 column feels like the screen take over that we have in the current mobile experience of modal and I thought no one liked that? 

Question: 
1. Are the 8 and 12 column examples just smaller width desktop views? 
2. Would the model always extend to the full height of the browser?

**Comment by oliviaflory** [comment]
@wonilsuhibm looks like Carbon has documented their different sized modals if we want to reference their calculations in determining sizes and max height? https://carbondesignsystem.com/components/modal/usage#modal-sizes

**Comment by wonilsuhibm** [comment]
The final studies are here: https://ibm.box.com/s/i7gcopwy2vk242h1yfp9ih2ewegogsny
