### ISSUE TITLE
Leadspace: Button wrapping

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1185]
Viewed on Chrome

In the Large breakpoint button text wraps to 2 lines and makes buttons taller.
Example from storybook:
![image](https://user-images.githubusercontent.com/57198117/73092390-8716c400-3eaa-11ea-8825-a4f9868402ab.png)

Instead, when button text is too long to fit on one line side by side, buttons should stack like this:
![image](https://user-images.githubusercontent.com/57198117/73092907-7a46a000-3eab-11ea-9a97-7c75d0b74b4f.png)

**Comment by larahanlon2** [comment]
After speaking with Lila, Andy, Jeff and Olivia we agree that this is no longer an issue. For now, we will not stack buttons on large breakpoints due to the dev cost and implications. Authoring side will enforce character count and we will provide guidelines in our documentation. In addition, we will stack buttons on medium breakpoint so the content has more room.
