### ISSUE TITLE
Content Section: Create the sub-pattern per functional specifications

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1198]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
have a core sub-pattern available for Content sections

> so that I can:
build section level patterns with this core consistent pattern

#### Additional information

 - Functional specifications: https://ibm.ent.box.com/file/604984417521
 - Currently baked into the `CardSection`, part of the work should abstract this out of the `CardSection` and then have that pattern utilize the `ContentSection`

#### Acceptance criteria
 - [ ] Create the `ContentSection` per functional specifications
 - [ ] Separate out from the `CardSection` and use the `ContentSection` within that pattern
 - [ ] Storybook stories added with corresponding knobs
 - [ ] README documentation added
 - [ ] Minimum 80% unit test coverage

**Comment by photodow** [comment]
@jeffchew it might be worth using the Content Block sub-patter on the right side of this layout because I've seen designs where their is also an optional title, and the text on the right side line up with the text within the card block, also I've seen they allow for a CTA at the bottom. Here's an example...

![image](https://user-images.githubusercontent.com/3793636/73182674-15738b80-40df-11ea-967b-13cd09da4b60.png)
