### ISSUE TITLE
Investigate why the firewall in the India office is blocking the images

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1316]
#### User Story

> As a `[user role below]`:
QA tester

> I need to:
have the images properly render on the desktop

> so that I can:
verify the code is working properly

#### Additional information

 - This issue originally surfaced testing the `lead space with images` pattern
 - Lead space defect (#1262)

#### Acceptance criteria
 - [ ] The firewall issue is addressed and the images are visible on the desktop
- [ ] All storybook stories have the FPO replace the images

**Comment by RobertaJHahn** [comment]
Transferring Issue (#1262) comment from Praveen:  As discussed on call,  images are rendering from "https://picsum.photos/id/1003/1056/480" due to security policy.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/57c21d1f-dab0-44dc-9eba-aeec7ae0f24e)

cc:  @Praveen-sr @chetankan

**Comment by kennylam** [comment]
@wonilsuhibm @oliviaflory @larahanlon2  FPO images from the `picsum` can't be viewed by our QA team because their firewall has a rule in place blocking that domain.
So patterns like these...
![image](https://user-images.githubusercontent.com/909118/74852593-ca7a1c00-530a-11ea-87fe-1c7f74e849c3.png)
![image](https://user-images.githubusercontent.com/909118/74852632-d8c83800-530a-11ea-98a5-45fb343a74bc.png)

...do not show an image at all, only alt text.

Until we find a solution which works for them, I suggest using plain ol' FPO boxes with the dimensions listed. I found one that lets you use custom colors as well:
https://fpoimg.com/
![image](http://fpoimg.com/300x250?text=Preview&bg_color=e74091)

**Comment by oliviaflory** [comment]
I like the idea of FPO boxes, that way we don't have random photos that don't comply with the Design Language photography guidance in the patterns as place holders. Are we specifying dimensions or aspect ratios @wonilsuhibm @larahanlon2 

We could specify a custom color from the IDL pallet for the FPO boxes.

**Comment by RobertaJHahn** [comment]
This approach was approved by Jeff.  The Dev's will update the storybook stories.
