### ISSUE TITLE
Embedded video player:  Create the visual specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1350]
This is to create visual specs for the Kaltura video player, the design of which came from Brand team.  Dev needs to understand the spacing and other specs that surround the video player itself.  

UPDATE 3/30/20: This task changed to creating the visual spec for "Media" component, which contains both the previous "Video" and "Image with caption" components".

### Additional Information
- It should match the image with caption component specs [here](https://github.com/carbon-design-system/ibm-dotcom-library/issues/748)
- Prod QA issue (#1143)

### Acceptance criteria
- [x] visual specs are available in PDF on Box
- [x] Associated Git stories have been updated with the new name and link
- [x] Add or update README Box note with a link pointing to the hosted files
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Box work is finished

**Comment by sethibm** [comment]
@RobertaJHahn @ljcarot I think this task needs a bit of resizing.  After chats with Olivia, Lara, Wonil, James, and Kenny, a few things surfaced.  

1) Merging the Image and Video component into one component, which for now, can be called the Media Component.  
2) Some ontology work around this to be sure that we are on same page and direction
3) Confirming that an inline and lightbox version is possible and desired both both image and video

For now, it seems like the adjustment for my immediate work on this task is to lay out the inline specs for video, in the same document where image + caption is visually specified (and using much of the same look, spacing, etc.).  And trying to match up with the currently coded version that Kenny is working on.  I can also take a rough start on the lightbox version, but we have no previous reference visual specs for this, as far as I can see.

The rest deserves some work / reflection per the above.

**Comment by ljcarot** [comment]
@sethibm Are you saying you're blocked or that you need to alter the scope of this issue and add additional issues.?  If we need 30 min call to clarify next steps, can you pls set up?

**Comment by sethibm** [comment]
@ljcarot No blocks at the moment, but I think we need to create at least one new issue focused on consolidating Image with Captions and Video Player into new Media Component (and sunsetting those previously separate ones) 

There will be small things like how the user will select and display image vs video within the component, and imagine some other items.  

It may help to have a short meeting about specific needs / todos around a merged Media Component?  I have so far talked with Wonil, Olivia, Lara, James, and Kenny on these developments, though am not sure who's needed to lock down next steps beyond the immediate parts I'm doing now.  Thoughts?

**Comment by ljcarot** [comment]
@oliviaflory Can I ask you to please set up a call so we can discuss next steps?  thx

**Comment by oliviaflory** [comment]
@ljcarot Yes, happy to set up a call

**Comment by sethibm** [comment]
@RobertaJHahn @ljcarot @oliviaflory @wonilsuhibm I've finished this design spec, but some re-organization is needed, because this component is now a merger of "Video player" and "Image with captions" into one spec and component: **Media with caption.**

It may help to view the PDF spec:
[Media-with-caption--design-spec.pdf](https://github.com/carbon-design-system/ibm-dotcom-library/files/4382159/Media-with-caption--design-spec.pdf)

And here is the new folder for Media with caption: https://ibm.box.com/s/4qexwczxfk1urqih8p0wucotfq0x2wd2

I think QA can occur apace for just video player part, but we should note to QA team to focus on this part of the spec?  We probably also need to shift the naming on related Zenhub tasks, to be clear on this change?

For housekeeping and updates overall, I placed the relevant files from previous components into this folder.  There is a Functional spec folder, with the previous docs for both Video player and Image with captions.  These docs need to be updated and merged into one functional spec for Media with caption.  Possible to create a task for this to be completed?  I'm not sure who writes these specs, so I may not have tagged him / her here.  It seems like a quick task, especially with the final design spec complete and available to help.

Please note: From the Video Player functional spec, section 2.2 Link is no longer a part of this overall spec and will be part of "Link with icon" component.  I have put a rough design spec file for this into the Link with icon component folder on Box.  So this part should not be included in the revised functional spec for Media with caption.  

It may help to quickly meet on this to clarify, or message on Slack, please let me know.

**Comment by sethibm** [comment]
@RobertaJHahn @ljcarot Update: Chatted and met with @photodow and @wonilsuhibm on naming and ontology map for this component and overall component that will hold these items (ie Video / Image / Media, Caption, and respective padding / styling).  James is showing @jeffchew rough diagram we made on potential adjustment to ontology.  Will update asap.

**Comment by sethibm** [comment]
@RobertaJHahn @ljcarot I believe this one is done.  I have updated the specs for this to be called "Media", per the latest ontology diagram @photodow made on Friday:

![media-ontology](https://user-images.githubusercontent.com/58601040/77922269-d7295280-726e-11ea-9f4c-f2291cb03cb3.png)

Here is the latest PDF of the design spec for Media:
[Media--design-spec.pdf](https://github.com/carbon-design-system/ibm-dotcom-library/files/4403353/Media--design-spec.pdf)

Sketch file is updated as well.  This is the box folder, with folders for Design spec, Functional spec, Ontology and References
https://ibm.box.com/s/4qexwczxfk1urqih8p0wucotfq0x2wd2

<img width="415" alt="Screen Shot 2020-03-30 at 10 14 39 AM" src="https://user-images.githubusercontent.com/58601040/77922976-c62d1100-726f-11ea-8fa9-f6ea96baedbf.png">

I'm not sure where the tasks are for updating functional specs, but part of the todo for those stories should likely be updating this folder, where I put the previous functional specs for "Image with caption" and "Video".  The latest names for functional specs, per ontology, are:

- Image
- Video
- Media
- Media Switcher

cc @wonilsuhibm

**Comment by sethibm** [comment]
@wonilsuhibm 

This one is done, save for the last item in checkbox, "A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when Box work is finished".  I'm not sure if they can do all-around QA if the related functional specs for the Media component are not done or updated yet?  James said he'll be doing this during the current sprint.

I think I can move ahead and do the QA on the existing component though meanwhile.

**Comment by wonilsuhibm** [comment]
@sethibm Thank you. 

Re prod QA, they will start once fund specs are made available by James.

Yes, please move forward with the design QA.
