### ISSUE TITLE
Table of contents: side menu type colors

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#1388]
## Table of contents: side menu type colors

-->

## Detailed description

> Describe in detail the issue you're having.

The current active state/other menu items on the side menu don't have correct color tokens.

Current: 
active menu item color value #161616
non active menu item color value #393939

Needs to be:
active menu item color value #171717
non active menu item color value #565656

<img width="518" alt="Screen Shot 2020-02-12 at 11 31 56 AM" src="https://user-images.githubusercontent.com/56400049/74360777-487a7800-4d8b-11ea-930f-ffa3ab982e50.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Table of contents

> What browser are you working in?
Firefox

## Steps to reproduce the issue

1. Go to [Table of contents](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--manually-define-menu-items)
2. Right click and click inspect
3. Inspect color on active and non active menu items in table of contents

**Comment by ljcarot** [comment]
I would suggest Severity 4, does not need to be fixed for Feb release.

**Comment by wonilsuhibm** [comment]
@RaphaelAmadeu please correct me, but i thought if we used color tokens, this kind of discrepancies would not happen — can you let me know why this is happening?

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm currently we are using the color tokens, I've checked [Carbon Color Tokens](https://www.carbondesignsystem.com/guidelines/color/usage/) and there's no tokens for #171717
nor #565656.

**Comment by oliviaflory** [comment]
@wonilsuhibm  @RaphaelAmadeu 

The colors are correct, #171717 and #393939 are the updated values for $text-01 and $text-02

The specs must have been written *before* Carbon updated the color pallet, so that's why they _seem_ to be wrong. This is a great example of why I'd suggest we don't write out exact HEX values in spec files and utilize the tokens because the tokens should ensure we are using the correct values (in theory).


No updates are needed and this issue can be closed

**Comment by RobertaJHahn** [comment]
Closing issue based on Olivia's comments above.
