### ISSUE TITLE
Pattern: Card Section - simple, vertical spacing is incorrect

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#1498]
(This is the design QA outcome of task #1276. Abstract link can be viewed [here](https://app.abstract.com/projects/736617ba-6c6d-4ab0-a5ae-76de9f81ec42/branches/master/collections/2966a52f-3c38-414b-badf-10865dfbaf60))

## Detailed description

**Describe in detail the issue you're having:**
Vertical spacing is not set up correctly. 
![Screen Shot 2020-02-26 at 4 23 59 PM](https://user-images.githubusercontent.com/45213839/75393786-7516af80-58b4-11ea-9c46-bb1169f830e7.png)

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect.

**Is this issue related to a specific component?**
Card Section - simple.

**What did you expect to happen? What happened instead? What would you like to see changed?**
The vertical spacing should be consistent across different breakpoints.

**What browser are you working in?**
Firefox and Chrome.

## Steps to reproduce the issue
Open [Storybook pattern](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-cardsectionsimple--default) and scale the browser window.

**Comment by oliviaflory** [comment]
I noticed a small discrepancy between the Card Section Simple and Card Section with Images.

I spoke with Lila about the spacing between the headline "Read more about it" and the cards, because two patterns are so similar, they should actually use the same space between the headline / cards at the medium and small breakpoints.

Lila confirmed we should maintain 64px spacing between the headline and text, so the Card patterns are the same. I think the vertical spacing might be correct for the headline / card relationship.

|<img width="404" alt="Screen Shot 2020-02-27 at 5 25 26 PM" src="https://user-images.githubusercontent.com/45692622/75493977-29820580-5989-11ea-879a-e41276d7edd7.png">|<img width="496" alt="Screen Shot 2020-02-27 at 5 25 08 PM" src="https://user-images.githubusercontent.com/45692622/75494006-3c94d580-5989-11ea-8215-54981ab833e8.png">|
|---|---|
| *Should be* 64px | Maintain 64px |

---
**However the spacing within the card is still a valid issue we should address**
