### ISSUE TITLE
Build issues with the DotcomShell in create-react-app

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#154]
## Detailed description

> Describe in detail the issue you're having.

When adding the DotcomShell in a vanilla create-react-app, getting the following error:

`File to import not found or unreadable: @carbon/layout/scss/breakpoint.
      in /Users/jeff.chew@ibm.com/Desktop/library-test/library-test/node_modules/carbon-components/scss/globals/scss/vendor/@carbon/grid/scss/_mixins.scss (line 12, column 1)`

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

`DotcomShell`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The page loads.

> What version of the IBM.com Library are you using?

`v1.0.0-rc.0`

## Steps to reproduce the issue

1. Create a new `create-react-app` application
2. Follow the steps to add the DotcomShell to the page
3. See error

**Comment by photodow** [comment]
I've seen this multiple times. I don't think this is specific to the `DotcomShell`. I think this is more of an issue on Carbon's side. They are inconsistently using `~` in their builds. I usually do two things to fix this issue on my end, but I think only the following is necessary.

Use `includePaths` within the `webpack.config.js`
https://github.ibm.com/james-dow/dotcom-boilerplate/blob/master/webpack.config.js#L31-L33

I think we really need to put in an issue with Carbon to see about fixing this.

**Comment by jeffchew** [comment]
After fierce googling, I came across this:
https://medium.com/@moog16/working-with-sass-create-react-app-v2-69c9629319b1

The short of it is that if you create a `.env` file at the root and add in the following, it works:
`SASS_PATH=./node_modules`

I might add this somewhere in the documentation.

cc: @photodow @kennylam @annawen1

**Comment by photodow** [comment]
@jeffchew that's the second method I've used, and it hasn't been as consistently successful.

**Comment by kennylam** [comment]
@jeffchew @photodow @annawen1 Or we stop hoisting all packages to the root `node_modules`. This was an issue early on, and James is right, it's definitely an issue on Carbon's side.

in `packages/react`
![image](https://user-images.githubusercontent.com/909118/66150896-2eae7480-e5e4-11e9-9769-88b185756290.png)

in `root`
![image](https://user-images.githubusercontent.com/909118/66150943-47b72580-e5e4-11e9-9205-f4ac17480239.png)

Adding `~` will fix things in our library but eventually it's going to look for something that's been hoisted to root, which in my case is
```
./node_modules/@carbon/ibmdotcom-react/es/components/Footer/LocaleButton.js
Module not found: Can't resolve '@carbon/icons-react' in '/dotcomlib-test/node_modules/@carbon/ibmdotcom-react/es/components/Footer'
```
because those aren't being installed in `packages/react/node_modules`.
