### ISSUE TITLE
Learn Page- Leadspace image is not getting loaded on mobile

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1617]
Issue:- On learn page, in leadspace section image is not getting displayed on mobile devices instead grey line is displayed.

## Steps to reproduce the issue

1. Enter the url in the browser.
2. Click on 'Learn' card.

## Additional information
URL:- http://ibmdotcom-nextjs-staging.mybluemix.net/learn

OS:- iOS(12, 13), Android (8,9)
Browsers:- Safari, Chrome, Samsung, UC![Leadspace with no image on learn page.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/50dc7b2e-586a-474a-88e6-49a3f397d260)

**Comment by jeffchew** [comment]
@reesedownes this might be the way the `LeadSpace` is configured, can you check?
https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-test

**Comment by reesedownes** [comment]
@jeffchew as far as i can tell, it seems that when the page is more narrow than the mobile breakpoint and the LeadSpace image is shown, the `defaultSrc` property isn't being rendered into an <img `src="defaultSrc"` /> property.

<img width="499" alt="Screen Shot 2020-03-30 at 3 50 03 PM" src="https://user-images.githubusercontent.com/38012976/77956021-2f784880-729f-11ea-9e37-e5835310b17b.png">

should the below be `default` instead of `defaultSrc`?

```
<LeadSpace
  type="centered"
  theme="g100"
  title="Lead space title"
  copy="Use this area for a short line of copy to support the title"
  gradient={true}
  // buttons={buttons}
  image={{
    sources: [
      {
        src: 'https://dummyimage.com/320x370/ee5396/161616',
        breakpoint: 'sm',
      },
      {
        src: 'https://dummyimage.com/672x400/ee5396/161616',
        breakpoint: 'md',
      },
    ],
    defaultSrc: 'https://dummyimage.com/1056x480/ee5396/161616',
    alt: 'Image alt text',
  }}
/>
```

i ask because in **leadspace.js** in the react package, it seems to be looking for `image.default`:

```
function imageClassname(type, image) {
  if (type === 'centered') {
    return (
      <div
        data-autoid={`${stablePrefix}--leadspace--centered--mobile__image`}
        className={`${prefix}--leadspace--centered--mobile__image`}>
        <img src={image.default} alt={image.alt} />
      </div>
    );
  } else
    return (
      <Image
        sources={image.sources}
        defaultSrc={image.default}
        alt={image.alt}
      />
    );
}
```

**Comment by jeffchew** [comment]
@reesedownes I think I remember bringing this up before, where it should be `defaultSrc` instead of `default`, since it should be following the `Image` props structure. Trying to find out if I opened an issue for this or if we landed on it being `default`. Can't seem to find it but I think that's the reason.

**Comment by reesedownes** [comment]
@jeffchew then i assume the fix might be as simple as just changing all the references to `defaultSrc={image.defaultSrc}` in the react package, but you can tell me how you'd like me to take care of it.

**Comment by reesedownes** [comment]
@jeffchew two questions on this: 

1) i made the change in the nextjs app, but i'm assuming i should also push code for the react package change, right? should that be a separate story?

2) should i make a story about the documentation re: how to yarn link the ibmdotcom-react library to next js locally?

**Comment by jeffchew** [comment]
> 1. i made the change in the nextjs app, but i'm assuming i should also push code for the react package change, right? should that be a separate story?

What changes do you need to make for the react package? Depending on the context, you may not need to open a new issue for it but certainly a different PR (since it's a different codebase obviously)

> 2. should i make a story about the documentation re: how to yarn link the ibmdotcom-react library to next js locally?

Yes, that should probably be its own story and PR.

**Comment by reesedownes** [comment]
@jeffchew thanks, got it. this is the issue i created for creating the documentation:

https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/1997
