### ISSUE TITLE
Horizontal rule is not being rendered from a number of Content Block patterns

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1653]
In v1.5.0-rc.0 for the following content block patterns:

- ContentBlockMixed
- ContentBlockSimple
- ContentBlockSegmented
- ContentBlockMedia

The horizontal rule is not being rendered at the pattern level.

**Comment by photodow** [comment]
@kexuibm based on the designs the horizontal rule has to be applied at the section level because unlike the blocks, link list and such it spans the full 12 columns to the end of the grid. We created an prop you can pass into the `Layout` sub-pattern that adds a modifier with the horizontal rule within `1.5.0-rc.0` I believe. Here's an example of how to use it, and the storybook for you to further review. Applying it this way will also help keep your page in alignment with the grid as well.

```jsx
<Layout nested={true} type="2-1" border={true}>
  <div>
    <ContentBlockSimple ... />
  </div>
  <div>
    <LinkList ... />
  </div>
</Layout>
<Layout nested={true} type="2-1" border={true}>
  <div>
    <ContentBlockMixed ... />
  </div>
</Layout>
<Layout nested={true} type="2-1" border={true}>
  <div>
    <ContentBlockSegmented ... />
  </div>
</Layout>
```

http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-layout--default
