### ISSUE TITLE
Pattern:  Card Section - Simple has 1 property to represent both the heading and the aria but these 2 may be different content fields

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1662]
v1.5.0-rc.0

For the CardSectionSimple pattern, within the cards prop, the heading property is used to render both the heading as well as the aria label for the heading.   However in the CMS there are 2 different fields for this which may have 2 different rendered values.  So is it possible to make the aria label are different property under the cards property for CardSectionSimple pattern?

#### Additional Information
 - [Accessibility standards](https://www.w3.org/TR/wai-aria/#aria-label)

**Comment by jeffchew** [comment]
As this is targeting the `v1.5.1` release, this cannot be worked on until we cut a `release/v1.5.1` branch.

**Comment by RobertaJHahn** [comment]
Praveen will ask Ram whether the aria label needs to provide an alternative text option that is different than the heading of the card.

cc:  @Praveen-sr @ljcarot

**Comment by jeffchew** [comment]
@kexuibm After reviewing and speaking with our accessibility tester/expert, he has explained that the `aria-label` is serving as a boundary around the card component so that the screen reader will know how to announce the card properly. Using the `heading` as the `aria-label` is actually the desired outcome, and that they should match in this scenario. 

With this said, this particular instance does not need an additional field to populate the `aria-label` and this feature request can be closed.

cc: @kennylam @RobertaJHahn @ljcarot
