### ISSUE TITLE
Landscape mode notification design study

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1706]
### user story
As a user of IBM.com, I want to know what to do when I view the site in landscape mode on my small phone which gives me almost no space to interact with anything on the screen, so that I can know how to view and use the site properly.

### Notes
- This is ao create a solution for the story, #1436
- Most likely, we will have to just display a notification which tells the user to use in portrait mode.

### Acceptance criteria
- [x] Design options (notification or alert styles, messaging, other visuals) have been explored
- [ ] Design direction is ready for the final design story

**Comment by jacobottesen-dgc** [comment]
Quick question to @wonilsuhibm 
Is Light Box Media viewer the only component that needs this message?

I looks like it's working ok in Firefox for me. 

![Screen Shot 2020-04-28 at 12.12.21 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/243d89be-021b-4bcc-a9ab-4c033f8f7696)

**Comment by jacobottesen-dgc** [comment]
Update: Currently working on design explorations for the notification. 

![Screen Shot 2020-04-29 at 11.30.30 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/5511a20b-1307-49a6-ab50-24143ae74ba0)

**Comment by jacobottesen-dgc** [comment]
@wonilsuhibm @oliviaflory 
I would love your input on which option works best for the icon.

![Screen Shot 2020-04-29 at 11.35.07 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/c5926317-f6fd-4d72-9922-ead5195efbda)

**Comment by oliviaflory** [comment]
These are looking really great @jacobottesen-dgc! My preferences are Option 1 and 4.

**Option 1**  The message is very clear because it shows the device in landscape and rotating to portrait mode. I don't see any other two toned icons in the system, so option 4 might be the way to go, or try adding some space where the two lines meet like the `Folders` icon that is trying to convey some depth of multiple folders

**Option 4** I prefer the arrow on the top, as apposed to option 3 where the arrow is at the bottom, it feels more intentional and for whatever reason it clicked faster for how my brain processed the imagery. 
 
**Option 2 and 5** are a bit weird for me because as an *icon* it should fit within a square container, and I fear these would get too busy when they scale down to fit within a square, especially at the smallest size for icons (16x16px).

---

**Some additional thoughts**

The line weight of the arrow in comparison to the device feels a bit off, when I look at the other icon examples the weights seem to match. Reference `Rotate clockwise` on the [Carbon icon page](https://www.carbondesignsystem.com/guidelines/icons/library)

Have you considered trying these as pictograms? From your layout explorations above it looks like this might be good at a larger size than an icon is intended to be. Icons can be sized at 16, 20, 24 or 32px, where as pictograms can range from 32px and larger.

**Comment by jacobottesen-dgc** [comment]
@wonilsuhibm @oliviaflory 

Here are some copy options for the landscape notification. Let me know your thoughts on which option makes the most sense to you. I'm leaning toward option 4.

1. Please rotate your device. This component is optimised for portrait mode.

2. Please rotate your screen. The media viewer is best optimised for portrait mode.

3. Please rotate your device. The media viewer is best viewed in portrait view.

4. Please rotate your device. This media viewer is best viewed in portrait mode.

5. Please rotate your device. This media viewer is optimised for portrait mode.

**Comment by jacobottesen-dgc** [comment]
Feedback during team design critique:

- We decided to go with: "Please rotate your device. This content is optimized for portrait mode." for copy on the notification. 
- Explore colors with notification
- Explore toast style notification not modal
- IDL doesn't do center aligned text explore left aligned

**Comment by jacobottesen-dgc** [comment]
After getting feedback from Olivia & Lara this is design we are leaning towards: 
![Screen Shot 2020-05-08 at 3.25.04 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/b556d2ef-52ee-469d-9451-5fc5d038e8f6)
