### ISSUE TITLE
Create RFC for an expressive moment in a Carbon core component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#1782]
#### User Story

> As a `[user role below]`:
Carbon adopter

> I need to:
have an expressive moment available in [decide which carbon component] available

> so that I can:
utilize in my application that requires a marketing/editorial look and feel

#### Additional information

 - Should use the existing Carbon Expressive theme as a reference (https://carbon-expressive.mybluemix.net)
 - Ideally would be a prop that's passed into the component which sets the variant
 - One thought would be to be a class modifier with the variant styles, but would need to see if there is a better way to approach this

#### Acceptance criteria
 - [ ] Open an RFC on Carbon's repo with the component variant available
 - [ ] Provide details from a design and dev perspective on what was done and why
 - [ ] Reach out to Carbon team to schedule a walkthrough of the RFC

**Comment by oliviaflory** [comment]
After meeting with the Carbon team today they asked us to try two additional components, button and text input. 

Jeff, Wonil, Anna and I agreed we only needed to address **one size variant** of the button because we believe adopters of the expressive theme only need one size (default 48px) of each component.

@annawen1 here are the specs for the default button variant, including the Carbon default and Expressive changes for comparison.

![Button - Specs - White theme](https://user-images.githubusercontent.com/45692622/78708022-74bffa00-78df-11ea-9042-1830b3ce07ce.jpg)

**Comment by oliviaflory** [comment]
@annawen1 here are the specs for text input

Carbon has recently added different sizes for _some_ of their form components, I didn't see size variants for everything yet.

When were were first doing the proxy approach Carbon only had the `default` size which is 40px tall and we were altering it to be 48px.

Now they have added `Extra large size (XL)` that is 48px tall which is what we want for the Expressive variant. I'm wondering if it would be easier for you to apply the expressive variant knob to the XL size vs the default size? Not sure what would be best considering they haven't added size variants for everything, and it might be a little weird that the expressive ones change between "regular" and "xl". 
cc: @jeffchew @wonilsuhibm 

I did the Carbon reference specs with the default size because I didn't notice the size variants at first



![Text input - Specs - White theme](https://user-images.githubusercontent.com/45692622/78931243-a4077000-7a73-11ea-8f2b-6bf372fd5ecf.jpg)

**Comment by annawen1** [comment]
@oliviaflory hmmm since we are applying the expressive variant to the `default` button size only...I feel it would be confusing to pick the `xl` of the input field documentation-wise. I'm thinking maybe we should stick with applying expressive to `default` for consistency

@jeffchew @wonilsuhibm thoughts?

**Comment by oliviaflory** [comment]
yeah... the "default" button technically is equivalent in height to the "XL" in other components, so the naming between components is a little off. But I'm cool with going for default all the way.

**Comment by RobertaJHahn** [comment]
This work is continued in Issue (#2044)
