### ISSUE TITLE
Component: Update the CTA functional specifications for the Solutions page changes

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1819]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `CTA` functional specs 

> so that I can:
so that I can properly code the `CTA` component that meets the Solution template requirements

#### Additional information 
 - Development issue (#1842)
 - [Airtable](https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T?blocks=hide)
 - CTA [[Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/components-cta--default)] [[Code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/components/CTA)] [[Directory](https://ibm.box.com/s/unvd38oewwguycqoqg0et75eluiiqhg6)]
 - Feature Block [#1834] [[Directory](https://ibm.box.com/s/fort8v1pj93z0ax6zgipcu0mbxsuwry1)]
 - Link List [[Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-linklist--default)] [[Code](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/patterns/sub-patterns/LinkList)] [[Directory](https://ibm.box.com/s/dgnfrnpaqepbuyifa04aoc091v4cnz3d)]

#### Acceptance criteria
 - [ ] Documented `CTA` functional specifications
 - [ ] Sent and/or presented the specs to Design, Content Strategy and Dev for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints
- [ ] Send a message to Jeff to let him know that the functional specs are ready for a developer by tagging him in the dev issue.

**Comment by photodow** [comment]
@kathysaraf I was going in adding some details and links to this story. We might still need to track down some answers for this update, and whether it's still relevant or not. The original thought was that we would need to update the CTA to allow for a list of text links like LinkGroup, but we've since pivoted realizing that wasn't necessary and we'll handle the list via the existing LinkList #1254. Does it need to be updated with feature block #1803, or should we handle those types another way. Let's sync up tomorrow and maybe figure out what we're going to do. We may need to pull in another story and let this cook a little longer.

**Comment by kathysaraf** [comment]
@photodow Sounds good - we can discuss the above and see what the alternatives are for other stories for this sprint if we determine no changes needed for now on this one.

**Comment by RobertaJHahn** [comment]
Discussed in the April 27 engineering meeting.
