### ISSUE TITLE
Pattern: Develop Callout - quote - Prod level version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1853]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Callout - quote`

> so that I can:
provide the ibm.com adopter developers patterns/components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Design specs issue (#2002  )
- [Visual and design specs Box link](https://ibm.ent.box.com/folder/110327678801)
- Functional specs issue (#1830  )
 - Callout [#1809] [[Directory](https://ibm.box.com/s/6b6pdgql2y3zxja2soj058t0ev8zwzik)]
 - Quote [#1806] [[Directory](https://ibm.box.com/s/0hjsr1foe5y849xs6ixc5g25uf9lgjr6)]
- Design QA testing issue (#2116 )
 - Prod QA testing issue (#2115 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
 - [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by ltitle** [comment]
@RaphaelAmadeu I am reviewing this pattern and want to confirm that authors would be able to create 3 lines for the source attribution. In storybook I only see fields for two but that may just be because they are the two different styles and if the cardinality was larger in authoring they could show three. This is the outcome I am looking for where there can be 3 lines. 

![image](https://user-images.githubusercontent.com/57198117/82059400-fb60b780-9693-11ea-8890-393e0904f93a.png)

**Comment by RaphaelAmadeu** [comment]
@ltitle 
Currently we only have 3 lines when the text length exceeds the container maximum width.

**Comment by ltitle** [comment]
@RaphaelAmadeu In the content model and authoring experience they will be allowed to create a cardinality of 3 fields. Should I open a bug for this?
