### ISSUE TITLE
Updates to functional specifications for patterns that include the ImageWithCaption or VideoPlayer

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2025]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
see updated specifications for patterns that utilize the `ImageWithCaption` or `VideoPlayer`

> so that I can:
see which patterns can use either media type

#### Additional information

 - Dev story: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1672
- Updated specifications for the following patterns identified:
  - Content Block Simple
  - Content Block Segmented
  - Content Group Simple
  - Content Item

#### Acceptance criteria
 - [ ] Updated functional specifications for the patterns affected

**Comment by ellenchoi1** [comment]
Content Group Simple - https://ibm.box.com/s/einladcnn9zrfbmd0asuoywppr9zx7j9
- v1.2 uploaded to box with updates to reflect that Image with Caption can also be used (doc file)

Content Item - https://ibm.box.com/s/xfm17x7dwbe4z7kjk482b8hbpjasft7o
- already reflects that Image with Caption and Video can be used

@photodow do you want to do these two since the specs are currently in pages files and it's a small update?
Content Block Simple - https://ibm.box.com/s/7f8mb1xyqdu5pimx9k1xtpl7oqrme0qf
- needs update to reflect that Image with Caption can also be used 

Content Block Segmented - https://ibm.box.com/s/pkascpokk7ae4t3ixis98hmw4e5y1v56
- needs update to reflect that Image with Caption can also be used (pages file)
