### ISSUE TITLE
Link with icon design specs

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#2147]
### Acceptance criteria
- [ ] design specs are available for the two variations created from the previous story.

**Comment by oliviaflory** [comment]
Per our conversation today in our Design planning meeting (4/27) we will create design specs for an icon on the left and right of a text link and later determine guidelines for when to utilize the right or left icon placement.

**Comment by oliviaflory** [comment]
@larahanlon2 @wonilsuhibm would you mind reviewing and letting me know if anything doesn't make sense for these specs. 

Goal: Add specs for link with icon to support icon on the right or left of the text.

![Primary_Link_Text-and-icon](https://user-images.githubusercontent.com/45692622/81107971-01ada180-8ee6-11ea-8d53-7e7ebb386248.png)

![Primary_Link_Text-and-icon-themes](https://user-images.githubusercontent.com/45692622/81108065-20139d00-8ee6-11ea-939c-6282492f0ad7.png)

**Comment by wonilsuhibm** [comment]
This looks great. Thank you @oliviaflory Two minor comments:
- Should we start removing the visited state, starting with this? And add feature requests to remove them from other link components as well.
- The size notation, `8/.5` is confusing. Unless you are fully ingrained in how things are done, like Carbon members or us, `8/.5` translates to `16`. I understand that Carbon is doing it this way when there is no space, but this is very confusing. I suggest that we always add units, and use the equal sign. `8px = .5rem`

**Comment by larahanlon2** [comment]
Looking good to me.

My only question is should we have another variation of this at a **smaller** size to accommodate for the `eyebrow` backlink we've been using in locale selector and masthead? In both of those components, I used `body-short-01` because 16px was too large. 

For **locale selector,** I think changing to what you have here:  blue link with icon component with `body-short-02` could work but it will give it a lot more prominence.

Locale current:
<img width="680" alt="Screen Shot 2020-05-06 at 10 15 06 AM" src="https://user-images.githubusercontent.com/53093550/81187766-76ceb480-8f82-11ea-81b3-f709f015f4c9.png">

Locale with new `link with icon`:

<img width="731" alt="Screen Shot 2020-05-06 at 10 13 15 AM" src="https://user-images.githubusercontent.com/53093550/81187608-47b84300-8f82-11ea-9466-6c189dc14f8b.png">

But for **masthead** L1 the 16px + blue wouldn't work. It's too large and the color would need an override. I know the devs have not yet completed L1 and it might change depending on Reboot IA team but I wonder if there will be future needs for a smaller `eyebrow` like this?

L1 eyebrow:
<img width="661" alt="Screen Shot 2020-05-06 at 10 10 40 AM" src="https://user-images.githubusercontent.com/53093550/81187308-e001f800-8f81-11ea-998e-f445264b9f1d.png">

**Comment by oliviaflory** [comment]
@wonilsuhibm 
> This looks great. Thank you @oliviaflory Two minor comments:
> 
> * Should we start removing the visited state, starting with this? And add feature requests to remove them from other link components as well.

This sounds good, I saw Carbon has disabled the visited link by default and has an option to add it in if the adopter chooses. 
We could do the same, or remove it entirely.

> * The size notation, `8/.5` is confusing. Unless you are fully ingrained in how things are done, like Carbon members or us, `8/.5` translates to `16`. I understand that Carbon is doing it this way when there is no space, but this is very confusing. I suggest that we always add units, and use the equal sign. `8px = .5rem`

Agreed, will add the px/rem I usually keep that but must have slipped off somehow.

---

> My only question is should we have another variation of this at a smaller size to accommodate for the eyebrow backlink we've been using in locale selector and masthead? In both of those components, I used body-short-01 because 16px was too large.

This is a good question.
I wonder if these cases are worth including a variant because:
1. The two situations don't follow the type size we are specifying for IBM.com, so do we want an adopter to be able to choose this variant? We could handle it through guidelines.
2. The two examples don't follow the theme color tokens of a `link` component (one blue, one gray), so one would need overrides no matter what. The masthead example seems to me like it should be a hard coded thing because it is so unique and the interactive states are different because hover and focus are in a container.
3. Are these cases unique enough to just spec them with the desired type size and variation?
4. I think the size of body-short-01 might change with the expressive theme, which would eventually break these designs. (maybe thinking too far ahead here).

These thoughts are stemming from the question: are we making too many things 'reusable'? Curious to hear your thoughts on this @larahanlon2 and maybe worth looping in a dev?

**Comment by wonilsuhibm** [comment]
Hmmm, this is a really good question. I feel that we should keep them as bespoke for now, and see if this becomes common enough.

**Comment by larahanlon2** [comment]
Ok cool @oliviaflory @wonilsuhibm I agree with all points an comments. At a minimum, I could see us updating `locale selector` to have the new `link with icon` which would leave Masthead L1 as the outlier. In that case, it's not worth adding a variant but something to track over time.

**Comment by oliviaflory** [comment]
@larahanlon2 if you think the larger link with icon component would work on in Locale selector that's alright with me!

I spoke to Lauren from Carbon and have a quick update to the theme specs, dark themes go to `blue-30` on hover:

![Primary_Link_Text-and-icon-themes](https://user-images.githubusercontent.com/45692622/81228282-d4cbbe00-8fbb-11ea-98d3-37077c668cf3.png)

updated structure to include `px/rem`
![Primary_Link_Text-and-icon](https://user-images.githubusercontent.com/45692622/81228309-e3b27080-8fbb-11ea-9cad-5b1ca592f828.png)

@wonilsuhibm I left the visited color, but thought we could reference this documentation, where Carbon has visited link style hidden until an adopter enables it? https://github.com/carbon-design-system/carbon/tree/master/packages/components/src/components/link
I can run it by one of the developers to confirm that's how we should do it. 

Unless you want to remove `visited` all together?

**Comment by RobertaJHahn** [comment]
@oliviaflory Moving this issue to sprint 20-10 so that you can close out your last question posted above.

**Comment by wonilsuhibm** [comment]
@oliviaflory turned off by default sounds like the right move to me. Can we move forward with that?

**Comment by oliviaflory** [comment]
Feature request created #2146
