### ISSUE TITLE
[CTA Section] Background color

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/ibm-dotcom-library#2357]
Background color for CTA section needs to be Gray 10, or ~~$ui-01 for White theme~~ **$ui-background for Gray 10 theme**

<img width="1393" alt="Screen Shot 2020-05-12 at 11 08 02 AM" src="https://user-images.githubusercontent.com/47458576/81718405-50f15600-9441-11ea-87a6-724e69e00c38.png">

**Comment by guilhermelMoraes** [comment]
@peter-garvin the visual specs points to the `$ui-background` as the token to the `background-color`, which is the one being used. 

Visual specs: https://ibm.ent.box.com/file/657510881851

**Comment by peter-garvin** [comment]
Could be that its intended to be ui-background for Gray 10 theme? @ltitle can you confirm?

I believe it should be taking after this:
<img width="561" alt="Screen Shot 2020-05-13 at 12 25 31 PM" src="https://user-images.githubusercontent.com/47458576/81844667-07723b00-9515-11ea-9a9d-d92a252b6d04.png">
<img width="751" alt="Screen Shot 2020-05-13 at 12 26 33 PM" src="https://user-images.githubusercontent.com/47458576/81844673-093bfe80-9515-11ea-87de-ae71b36b531e.png">

**Comment by guilhermelMoraes** [comment]
Hmm, I get it. Worth to mention too that the [functional specs](https://ibm.ent.box.com/file/654019882500)  isn't visually in pair with the visual specs - the background, I mean.

**Comment by ltitle** [comment]
@peter-garvin Yes the idea was that this uses gray 10 theme so that is why it has ui-background as the token.

**Comment by ljcarot** [comment]
@photodow Can you update the functional spec to specify the gray 10 theme and verify the comments above.  cc: @wonilsuhibm

**Comment by photodow** [comment]
@guilhermelMoraes we shouldn't be using the functional specs as visual spec references.

@ljcarot I haven't been including theming in the functional specs because it'd be a repetitive block of text on every functional spec since every component and pattern should be able to support all 4 themes duplicating a lot of work there that's a blanket statement. If that's something we want to change we can talk about how we might like to handle that (I would strongly encourage we don't include that in every spec due to maintenance and effort). Visual is already taken care of the tokens which in return visually theme the component/pattern itself.
