### ISSUE TITLE
Apply tokenization of container/icon/component level styles in Carbon

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2503]
#### User Story

> As a `[user role below]`:
Carbon adopter

> I need to:
have the ability to theme container/icon/type across all Carbon components

> so that I can:
apply an expressive theme for my application using Carbon

#### Additional information

 - We have had a number of conversations and RFCs regarding this work. This is to push in the finalized approach within the Carbon codebase in order to enable theming on the IBM.com Library side for an expressive theme
- Carbon core support: https://ibm.ent.box.com/notes/661849259762
- Implementation notes: https://ibm.ent.box.com/notes/656897915881
- Implementation questions of expressive styles: https://ibm.ent.box.com/notes/656526066704
- Latest code: https://github.com/carbon-design-system/carbon/compare/master...asudoh:alternate-type-space
- Task breakdown idea:
  - Cross-cutting work:
    - Code to define ibmdotcom-version of container/type/component tokens (`packages/components/demo/scss/demo.scss ` and `packages/react/.storybook/styles.scss` changes at https://github.com/carbon-design-system/carbon/compare/master...asudoh:alternate-type-space#diff-e5109c45c8ba1aba8cff307a5fe81543)
    - (Stretch-goal) Code in Carbon development environment to switch to ibmdotcom-version of tokens
  - Each component work:
    - Button
    - Checkbox
    - Code snippet
    - Combo box
    - Data table
    - Date picker
    - Dropdown
    - File uploader
    - Inline loading
    - Loading
    - Modal
    - Multi select
    - Notification
    - Number input
    - Overflow menu
    - Progress indicator
    - Search
    - Select
    - Structured list
    - Tabs
    - Tag
    - Text area
    - Text input
    - Tile
    - Time picker
    - Tooltip

#### Acceptance criteria
 - [ ] PR (or multiple PRs) opened in Carbon codebase to include tokenization to enable theming

**Comment by jeffchew** [comment]
@asudoh I created all of the stories so we can start staging the work. Given the number of stories, I am wondering if it makes sense to have you divide up the work with one or two other devs on the team. @annawen1 and @andysherman2121 have been helping with the initial proxy work, so perhaps they would be good candidates. You can show them where everything should go and what to look out for when creating the PRs in Carbon.

@oliviaflory @wonilsuhibm I have given a first stab at prioritization of these components but you can go through and assess if they all look ok.

We probably will want to create a separate story (or epic) to finally create the expressive theme and take advantage of all of these tokens getting introduced in Carbon, as well as any corresponding documentation, etc that we need to produce on how to apply it.

cc: @ljcarot @RobertaJHahn @wonilsuhibm @oliviaflory

**Comment by RobertaJHahn** [comment]
Carbon rejected the pull request as they do not have the resources to take on the work.  Closing the epic (#2503) and all of the linked issues.  

Copy of Jeff's email summarizing the next steps:  

_We have worked extensively with Akira Sudoh (former Carbon team member) and have recently created a comprehensive code contribution to Carbon to introduce API tokens that would enable the expressive theme. After review from the Carbon team, they have unfortunately rejected our code proposal, stating that it would be too much for their team to support at this time. They have taken considerable resource reductions and their team is much smaller than it was previously which most likely contributed to this decision on their end._

_With this news, our team is essentially back to supporting a proxy on our end. However, we have had very valuable learnings when working with Akira, and plan to execute on this new contingency plan:_
 
-  _Identify key Carbon components we would like to support in the expressive theme ◦We can begin with a set of essential components we would like to support, then expand over time_
 
-  _We will make full use of our automated visual regression tool that we recently stood up. This will be extended to our standalone storybook instance with the Carbon components that have the expressive theme enabled. The work that needs to be done here: ◦Activate visual regression testing for Carbon expressive components_
 -_Create additional e2e tests to cover all variants_
 
- _Take all of Akira's work, and apply the tokenization to the IBM.com Library instead ◦Rather than a hardcoded way of applying the proxy, we are thinking of having the API tokens as an offering from our team instead. This can be ultimately used by other IBM.com Library adopters if the need arises, plus adds more flexibility and scalability on our end_
 

- _Updates to documentation/design kits for our adopters ◦We will need to own and create all supporting documentation for the expressive theme, so there is some upfront and continuing work around this._


_We have almost all of the carbon components with a hardcoded proxy already in place so it serves as a very good starting point. We will be applying the action items above in order to future proof it as a manageable solution going forward._
