### ISSUE TITLE
Component level tokenization - Data table

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2522]
#### User Story

> As a `[user role below]`:
Carbon adopter

> I need to:
theme various tokens for the Data table component

> so that I can:
apply an overall theme in my application

#### Additional information

 - This is component-level tokenization work identified in the epic https://github.com/carbon-design-system/ibm-dotcom-library/issues/2503
- Latest code can be found at `_data-table-core.scss`, `_data-table-action.scss`, `_data-table-expandable.scss` and `_data-table-sort.scss` changes in: https://github.com/carbon-design-system/carbon/compare/master...asudoh:alternate-type-space

#### Acceptance criteria
 - [ ] Component-level tokens applied in Carbon

**Comment by RobertaJHahn** [comment]
Carbon rejected the pull request as they do not have the resources to take on the work.  Closing the epic (#2503) and all of the linked issues.  

Copy of Jeff's email summarizing the next steps:  

_We have worked extensively with Akira Sudoh (former Carbon team member) and have recently created a comprehensive code contribution to Carbon to introduce API tokens that would enable the expressive theme. After review from the Carbon team, they have unfortunately rejected our code proposal, stating that it would be too much for their team to support at this time. They have taken considerable resource reductions and their team is much smaller than it was previously which most likely contributed to this decision on their end._

_With this news, our team is essentially back to supporting a proxy on our end. However, we have had very valuable learnings when working with Akira, and plan to execute on this new contingency plan:_
 
-  _Identify key Carbon components we would like to support in the expressive theme ◦We can begin with a set of essential components we would like to support, then expand over time_
 
-  _We will make full use of our automated visual regression tool that we recently stood up. This will be extended to our standalone storybook instance with the Carbon components that have the expressive theme enabled. The work that needs to be done here: ◦Activate visual regression testing for Carbon expressive components_
 -_Create additional e2e tests to cover all variants_
 
- _Take all of Akira's work, and apply the tokenization to the IBM.com Library instead ◦Rather than a hardcoded way of applying the proxy, we are thinking of having the API tokens as an offering from our team instead. This can be ultimately used by other IBM.com Library adopters if the need arises, plus adds more flexibility and scalability on our end_
 

- _Updates to documentation/design kits for our adopters ◦We will need to own and create all supporting documentation for the expressive theme, so there is some upfront and continuing work around this._


_We have almost all of the carbon components with a hardcoded proxy already in place so it serves as a very good starting point. We will be applying the action items above in order to future proof it as a manageable solution going forward._
