### ISSUE TITLE
MegaMenu: Engineering design support - data model validation follow-on consulting

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3123]
#### User Story

> As a `[user role below]`:
DDS Designer working on the MegaMenu

> I need to:
have engineering support while working on the designs

> so that I can:
accelerate the design effort and improve the design quality

#### Additional information

 - This issues is created for the engineers to be involved during the megamenu design to validate that the existing data model will work with the designs.
- The duration of this work is for the second week of sprint 20-14.  This work is included in issue (#3122).  

#### Acceptance criteria
 - [ ] Data model analysis and recommendation are provided to Olivia

**Comment by annawen1** [comment]
instead of having the `highlightedSection` field populated with menuItems as shown in the previous initial ticket: MegaMenu: Engineering design support - data model validation #3122, we have added a `highlighted` boolean field to each menuItem that is set to render on the left panel of the megamenu design. This prevents us from having duplicate data as we still need the data to support v18. 

PR to edit the masthead files has been raised and merged.
