### ISSUE TITLE
Enable the Expressive Theme in the IBM.com Library and publish website content

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3127]
This is the epic that captures the enablement of the expressive theme for all of the components in the IBM.com Library by default. Work has already been completed for the expressive theme and made available in `v1.9.0`:
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2784

**Comment by jeffchew** [comment]
@RobertaJHahn @wonilsuhibm @ljcarot issues we need to add to this epic:
- Design kits
- Updates to guidelines (on the website)
- Production QA testing on the main storybook (after the theme has been enabled by default)
- Add release notes (and any other announcements we need to think about?)

**Comment by wonilsuhibm** [comment]
There would be pieces on the website:
- introduction to the expressive theme (a draft: https://ibm.box.com/s/9ikc4nmmwcaxxbpth78ywpflj6goxtev)
- adding component guideline pages (36+). This is a massive work.

**Comment by oliviaflory** [comment]
**Notes from slack conversation July 6**

**Jeff:** The plan was the remove the feature flag, but keep as an explicit import for now, right? And we have to then do some testing around the expressive theme applied to our current IBM.com Library components, and any fixes we need to do on our end in order to have the expressive theme turned on in the IBM.com Library by default?

**Olivia:** Some notes I took from when we talked last week, more specific to the questions I wanted to ask, if this helps:

```
Do we think we should theme all the components now that we will be maintaining them?
- In the proxy, all are turned on, globally. 

Should it be automatically turned on in the IBM.com Library? Should adopters need to opt into it?
- Should we allow teams to turn it off? Example: with the masthead, would teams ever need it in productive?

Design review of Expressive theme environment.
- Any issues we need to create
- Another issue to enable expressive theme globally on all of IBM.com Library.
    - Maybe not everything… maybe just masthead and footer.
- Maybe teams want the expressive theme outside of the Dotcom experience

Replicate Carbon components documentation on our website

Maintain full design kit, full themes. 

Operationally, can we do only some components?
```


Jeff, I do think that was what was proposed at the end of our call. I’m not sure if @wonilsuh had any concerns or follow up questions to that approach?

**Comment by oliviaflory** [comment]
**Slack conversation July 10**

 **Jeff** just confirming, we have decided to remove the feature flag carbon-expressive-experimental for the expressive theme? I can open a PR for this.

also, the way we're doing the tokens now it's not necessary to enable css custom properties, right?

secondly, we will need to create issues for enabling the expressive theme in the IBM.com Library by default, I'll create an issue for this

Issue created here: https://github.com/carbon-design-system/ibm-dotcom-library/issues/3126. Are we attempting this for v1.9.0 release or want to pace it for v1.10.0?

figured we have a bunch to do before we're ready for this, so I made an epic to track this: https://github.com/carbon-design-system/ibm-dotcom-library/issues/3127, with some suggested stories we need to create to go along with it

**Akira** Thank you for creating those issues! CSS custom properties are not needed for expressive theme proxy code, but other portions in our codebase have started replying on CSS custom properties, and thus making CSS custom properties a requirement makes sense And you are right that to use the proxy globally with other IBM.com library code in the same app, we need to change our component code

**Comment by oliviaflory** [comment]
**Slack conversation July 13**
just throwing this out there as an idea, since we will be enabling the expressive theme by default, wondering if it's worth including a scss flag like $dds--expressive-theme-disabled so that adopters can opt out of carbon expressive?

**Wonil** I think we want to discourage using productive as much as possible. I’m totally fine with not providing productive option at all initially. Once a team comes back to us with a hard proof that their experience performs better in productive, then we can start thinking about introducing productive.

**Decided: Expressive theme will be turned on by default**
