### ISSUE TITLE
Using components outside of IBM

### ISSUE THREAD

**Issue by ACAVJW4H** [carbon-design-system/ibm-dotcom-library#3137]
## Summary
I just saw that some storybook elements were revised and there are now guidelines on how to use react components thank you! Yet there were some additions specifying where we can use the components as well. I was under the impression that since the carbon library is open source and developers are encouraged to use it, and since this library is Apache2 licensed, we were free to use ibm-dotcom-library components in our projects with due attribution and notices. 

Would you folks be kind enough to clarify the use of the components outside of IBM.com? 

## Relevant information

![Screen Shot 2020-07-14 at 12 21 43 PM](https://user-images.githubusercontent.com/2772104/87410013-73812600-c5ce-11ea-8453-5fb3405ee6da.png)

**Comment by shinytoyrobots** [comment]
Yes, you can use the components in your projects under the Apache2 open source licensing.

The text here is guidance about how and where to use this within an IBM context (as, while we are open source, Carbon's primary purpose is to facilitate design and development for IBMers). So it's guidance for that, rather than intended to imply that this is *only* for use within IBM contexts.

**Comment by jeffchew** [comment]
Thank you for your question @ACAVJW4H ! And yes, I echo @shinytoyrobots's note that we are open source and can be used outside of IBM.

If this answers your question, I'll go ahead and close this issue!

cc: @asudoh @wonilsuhibm @ljcarot

**Comment by ACAVJW4H** [comment]
Thank you! This answers my question clearly
