### ISSUE TITLE
Investigate feasibility of v18 adopting the Web Components dotcom shell

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#3359]
#### User Story

> As a `[user role below]`:
IBM.com user

> I need to:
see the carbon masthead and footer on v18 pages

> so that I can:
see a consistent header/footer experience on IBM.com regardless of if the page is built on v18 or carbon

#### Additional information

 - Web components included should be masthead and footer
 - ~Should see how this affects pages that are configuring their L1's, etc and if those can be accounted for or not~
- Scope of this should be for L0 only. If someone configures L1, we will still serve up the old masthead/footer.

#### Acceptance criteria
 - [ ] Determine if there are any issues if introducing web components in v18
 - [ ] Should have v18 load the old masthead/footer if detecting IE11 
 - [ ] Identify any "gotchas", if any

**Comment by RobertaJHahn** [comment]
8/14/2020 Slack message from Jeff regarding investigation:
@asudoh @kenny.lam hey so I was able to get the masthead/footer to load into v18! The things I noticed though we need to figure out that might actually be issues with what's getting imported in the footer as the visuals don't look right... some observations:
Masthead seems to actually render fine! We need to figure out what to do with spacing of the content from the masthead though
Footer background is white?
Locale Modal wasn't running until I added the import manually. Added it into the PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/3579
The Locale Modal search results isn't loading in, need to figure out if that's also because of a missing import...
Locale Modal close button is missing
Current working branch is here: https://github.ibm.com/webstandards/v18/tree/feat/web-components
Some other observations I notices were missing codesandbox examples for footer and dotcom-shell. I also added those to the same PR, but other thing I noticed is that the masthead is looking for focuswrap in the utilities package, which doesn't exist yet since the direct dependency that it's looking at is v1.9.0 of utilities so that build is failing. This will hopefulyl clear up once we get rc.0 out. We should focus on all of the codesandbox examples though next week and fix anything that isn't rendering, and push as hotfixes if necessary (identifying any missing imports, etc)

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/abd7dc1a-99ee-4798-bcfc-9601e5d2746b)
