### ISSUE TITLE
External site pointing to an internal resource

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-dotcom-library#3634]
Loving the new site! 

Not so much a question, just general feedback/something to think about..

The link on this card points to a Slack workspace that is on the Enterprise Grid. So only IBMers have access to it. It might be worth exploring how to let me people know since this is a public facing site.

![image](https://user-images.githubusercontent.com/15822070/90645122-3296b580-e1fb-11ea-918b-04bbf929da49.png)

**Comment by RobertaJHahn** [comment]
@wonilsuhibm @JennySanchez Would this suggestion be something that you would explore?

cc:  @ljcarot

**Comment by JennySanchez** [comment]
Good point from Scott!

Since this is linked to the ibm-digital-design Slack channel and our goal is to make sure our adopters know where to start a conversation with our team. I think we should update the title from "Slack community" to "ibm-digital-design". Once we make the update, I'd also like to test it out to see if we need any additional Information to avoid the confusion.

**Comment by JennySanchez** [comment]
PR detail can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/634).

**Comment by RobertaJHahn** [comment]
@JennySanchez Can this issue be closed or should I move it to sprint 20-19?

**Comment by JennySanchez** [comment]
@RobertaJHahn The task is done and we can close it.
