### ISSUE TITLE
Create new Patterns overview page content

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#3700]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
Understand what patterns are and what is available/coming soon from the Library

> so that I can:
design new experiences following best practice design solutions

#### Additional information
- All layout patterns are moving to Components on the website (as per Storybook and patterns future state work). See [epic here.](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/497)
- As a result, we need a new patterns overview page
- There is MVP WIP content available [here](https://ibm.invisionapp.com/share/2PO04US6CX9#/319576752_Pattern-Overview-V5) that was created for future state prototype.

#### Acceptance criteria
- [x] Lara creates the new Patterns overview page
- [x] Jenny reviews the content 
- [ ] Wonil reviews and approves the content before publishing

#### Note
If we do not have pattern guidelines ready to publish at the time of publishing the overview page, we can update the table to saw 'coming soon'.

**Comment by larahanlon2** [comment]
Hey @JennySanchez @wonilsuhibm here's my new WIP `Patterns overview` page. Could you both take a look and share any comments/feedback/questions? 

A couple of notes from my side:
1. I tried to align the overview description with [Carbon's](https://www.carbondesignsystem.com/patterns/overview) whilst also adding our own IBM.com Library "flavor" to highlight things like digital content and webpages (the things that differentiate us from Carbon). Let me know what you think.
2. For the list of patterns, these are the ones I included in my earlier prototypes but I cleaned up the descriptions. As per our agreement to prioritize and publish the first three (cards, in-page navigation, lead space), I wonder: **should I keep the others here or would you prefer we remove until it's agreed that these will definitely be published?** If we keep them here we can add a "coming soon" tag, perhaps.
3. I didn't add any status tags in this table because we're not providing code but @JennySanchez if you would prefer to have tags here we could do something like `Published` and `Coming soon`.


![pattern--overview-v1 0](https://user-images.githubusercontent.com/53093550/92035895-674b5680-ed3d-11ea-886c-80cc07cb2fb3.jpg)

**Comment by wonilsuhibm** [comment]
@larahanlon2 Thank you! Regarding that "Similar to Carbon..." part, comparing this section to Carbon feels a bit awkward. I do think that connecting to Carbon's pattern section is a good idea. Maybe we can actually say something like "more patterns are available on CarbonDesignSystem.com" or something along this line? I also like the rest of the sentence that begins with "SImilar to Carbon", I think that the part that talks about reusable combination of... is helpful.

**Comment by JennySanchez** [comment]
Hi @larahanlon2 Thank you~🙏


**1. I tried to align the overview description with Carbon's whilst also adding our own IBM.com Library "flavor" to highlight things like digital content and webpages (the things that differentiate us from Carbon). Let me know what you think.**

For linking to the Carbon Patterns, we can add a "Card" below the list. Like how we treat the "Carbon Core Component" linking on the current [Component Overview Page](https://www.ibm.com/standards/web/ibm-dotcom-library/components).

![Screen Shot 2020-09-03 at 10.44.32 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/dca47cff-c406-4be4-9806-a0bfcb848dee)

**2. For the list of patterns, these are the ones I included in my earlier prototypes but I cleaned up the descriptions. As per our agreement to prioritize and publish the first three (cards, in-page navigation, lead space), I wonder: should I keep the others here or would you prefer we remove until it's agreed that these will definitely be published? If we keep them here we can add a "coming soon" tag, perhaps.**

TBD.

**3. I didn't add any status tags in this table because we're not providing code but @JennySanchez if you would prefer to have tags here we could do something like Published and Coming soon.**

For Patterns or Guidelines, we will not use tags, since it's dev driven. When a guideline is published, we will not need a "published" label. Because there will be a description and the guideline name will be turned into a text link and linked to its own page. 

---

**Question:**
Based on the principle of once a publishing work started, we should let the adopters know its availability asap. When it comes to Guideline, should we add it to the Guideline Overview Page table list right away and the description area will have "Coming soon" on it?

If the answer is Yes, then for Lara's note number two, we should include all the Patterns website pages we are going to publish. 

Thoughts?

**Comment by wonilsuhibm** [comment]
How about this as the description?

IBM.com Library patterns are guidelines tailored to meet IBM.com maker's needs to solve user problems effectively while establishing greater consistency across IBM.com. These are based on best practice design solutions for user-centered tasks, digital content types, and web page intents. They show reusable combinations of components, layouts, and flows that address common user objectives.

**Comment by larahanlon2** [comment]
@wonilsuhibm thanks! I like the start of that first sentence and the overall essence of what you're communicating. But the flow of it is a bit jarring as I read it so I wonder if it could be tweaked slightly or simplified. How about:

IBM.com Library patterns are guidelines that are tailored to meet the needs of IBM.com users and implemented by makers to establish greater design consistency across IBM.com. They are based on best practice design solutions for user-centered tasks, digital content types, and web page intents. They show reusable combinations of components, layouts, and flows that address common user objectives.

**Comment by larahanlon2** [comment]
@JennySanchez thank you! I like the idea of adding a card that links to Carbon patterns, just like the components page. 

I can see the benefit of adding a "coming soon" tag for guidelines and patterns from an adopter perspective. However, it might be hard to maintain from a DDS perspective. For example: if roadmap or priorities change you might end up with a list of "coming soon" items on the website for a long time or maybe you might need to remove some things altogether. Either way, I think it will work so I'll let y'all decide what's best!

**Comment by wonilsuhibm** [comment]
@larahanlon2 I like that update. Thank you!

**Comment by JennySanchez** [comment]
@larahanlon2 Agreed with you on your point, but at the same time, we need to figure out a way to solve adopter's pain point on how to find what IBM.com Library offers and what will be available to them. 

What do you both think...

For the Components (UI + layout), we add available item to the Components Overview Page table list as soon as the design is done. The upcoming component will have a description with under construction label.

For Guideline, we add available guideline to the  the Guideline Overview page table list as soon as the **content crafting started**. upcoming component will have a description with coming soon label.

Since the "design" and "content crafting" already started, the possibility of change might be smaller (hopefully none). In this case, we also can avoid a bunch of "coming soon". If it's an unavoidable change, then we will take it off the list.

**Comment by larahanlon2** [comment]
Sounds great to me @JennySanchez

**Comment by larahanlon2** [comment]
Updates:
1. The intro paragraph is updated with latest copy reviewed and agreed by Wonil in thread above.
2. I added a Status column to show how we could use tags based on thread above.
3. Card linking to Carbon's Production patterns added.

![pattern--overview-v1 2 copy](https://user-images.githubusercontent.com/53093550/92771848-37b5d300-f369-11ea-85e8-857fda2d3b14.jpg)
![pattern--overview-v1 2](https://user-images.githubusercontent.com/53093550/92771868-3ab0c380-f369-11ea-9f65-ca531f8914f3.jpg)

**Comment by larahanlon2** [comment]
One last change:
1. Updated the card title to read "Core production patterns" after reviewing with Jenny.

@wonilsuhibm @JennySanchez can you both take a look and give me your blessing if you approve this page? Once it's approved, I can create the markdown and have it ready for publishing next sprint, in tandem with [this issue](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/628).

![pattern--overview-v1 3](https://user-images.githubusercontent.com/53093550/92791173-756f2780-f37a-11ea-80c5-ead99514b6ce.jpg)
![pattern--overview-v1 4](https://user-images.githubusercontent.com/53093550/92791179-76a05480-f37a-11ea-82aa-59a8f16fd8d9.jpg)

**Comment by JennySanchez** [comment]
@larahanlon2 Looks great and as mentioned in our Slack conversation, any unavailable patterns page, we will take the text link treatment off.
