### ISSUE TITLE
React: Masthead - On empty search bar, clicking on search icon, page navigates to search results.

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#3990]
## Detailed description

Issue: On empty search bar, user clicking on search icon, refreshes the page and navigates to search results.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b3d12416-f182-43e9-add0-b6ac331aba71)

Landing page:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d1232021-545e-48c6-8b5e-30680da20e3b)

**Comment by IgnacioBecerra** [comment]
What should the expected functionality be for an empty search? We could make it so clicking the icon/pressing enter won't work until text is inputted, but searching for " " (space) seems to return all the IBM pages, which may be a better result for an empty search. Any thoughts?

**Comment by RobertaJHahn** [comment]
@photodow See the comment from @IgnacioBecerra above.  Can you answer his question?

**Comment by photodow** [comment]
@IgnacioBecerra I believe the expected behavior on the IBM.com Library side is the use clicks the search icon, and executes a search by redirecting them to the IBM.com search page. Our search component doesn't have any expectations beyond that, but from a personal standpoint I believe I would expect there to be maybe an unfiltered list of search results waiting for me.

@RobertaJHahn I don't believe this to be a bug on our end, unless the expectation is to change the functionality of the search component to not execute if the input value is empty.

**Comment by IgnacioBecerra** [comment]
@kennylam addressed this issue in #3939. The changes are currently live in the React-canary environment, which will eventually incorporated into the regular React release. Closing this for now -- if we still have issues after release we can reopen or create a new issue.
