### ISSUE TITLE
Cupcake website page creation - Get started/Coding page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#516]
_chsanche created the following on Oct 07:_  

 

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the code base and IBM.com library

> so that I can: do my day to day work efficiently.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/516.
- Develop page on v19a website can be viewed [here](https://www.ibm.com/standards/web/getting-started/developers.html)
- Developers page on the current Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/get-started/develop/react)

#### Task
- Collaborate with @Kenny-Lam for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1818_

**Comment by jeffchew** [comment]
_On Oct 10, chsanche commented:_
@Kenny-Lam Adding you to this issue for consulting and content collaboration purpose - FYI.

**Comment by JennySanchez** [comment]
FYI - Not sure why Lara is added to the issue and she is removed.

**Comment by jimpistilli** [comment]
Putting a few ideas below, but wondering what is the proper name of the page? 
Digital Design React Library? And is it "new"?

Otherwise here's a few ideas:

_Rapidly build beautiful and accessible experiences. The Digital Design React Library contains all the resources you need to get started. (Original)_

Create engaging and accessible experiences efficiently. The Digital Design React Library has the tools that you need to begin.  

Build beautiful and accessible experiences with the new Digital Design React Library. 

Develop engaging and beautiful web experiences with the Digital Design React Library. 

What are the two most important points of the library? Beautiful? Accessible? How about Engaging?  

cc: @JennySanchez @jacobottesen-dgc

**Comment by jacobottesen-dgc** [comment]
@jimpistilli
If you have sometime today could you look over this content draft? The draft is for the getting started dev page. I just want to make sure the content sounds great.
https://ibm.box.com/s/dtseffre66j841xkc805onra3e4jqesh

**Comment by JennySanchez** [comment]
@jimpistilli @jacobottesen-dgc 

IBM.com library is for coding/developer. This page tile is coding, so I think we need to focus on the language from a coder/developer's point of view. What is important to them when learning about the design system so they start a coding task as soon as they can. 

"Rapidly build beautiful and accessible experiences. The Digital Design React Library contains all the resources you need to get started". 

^^^ I like it, but we need to take the word" React" off, because we do not just support React.

**Comment by jimpistilli** [comment]
@JennySanchez Here are some ideas, many of the words are interchangeable:

- Create a beautiful and accessible web experience right away with the IBM Digital Design Library.
- 
- Create beautiful and accessible web experiences ASAP with the IBM Digital Design Library.
- 
- Develop engaging and beautiful web experiences quickly with the Digital Design Library.
- 
- Develop a beautiful and engaging web experience rapidly with the IBM Design Library. 

cc: @jacobottesen-dgc

**Comment by jimpistilli** [comment]
Attached is a work in progress version of the Getting Started/Coding page. Discussed with @jacobottesen-dgc, but need to see some of the components on the site to see how they are written, to write them actually on here.

https://ibm.box.com/s/254eglkvm8rww1qvu4gcqm8wi72mfqi2

@jacobottesen-dgc Also please download the Word doc and view it with Simple or No Markup, instead of viewing it on Box, as it will be much easier to read.

https://ibm.box.com/s/254eglkvm8rww1qvu4gcqm8wi72mfqi2

cc: @JennySanchez

**Comment by jeffchew** [comment]
@jimpistilli it should be the `IBM.com Library` and not the `Digital Design Library`.

cc: @JennySanchez @jacobottesen-dgc

**Comment by jimpistilli** [comment]
- Create a beautiful and accessible web experience right away with the IBM.com Library.

- Create beautiful and accessible web experiences ASAP with the IBM.com Library.

- Develop engaging and beautiful web experiences quickly with the IBM.com Library.

- Develop a beautiful and engaging web experience rapidly with the IBM.com Library.

@jeffchew Thanks, updated above. To do the other half of the request, I need to see how #1 and #4 is written on the site but I can't seem to find them. Would you be able to send screenshots?  Thanks.

![image](https://user-images.githubusercontent.com/32171262/67398031-16dd6700-f578-11e9-8cf2-7d8048fdcde3.png)

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Here is a word doc Jim by created with the final content: https://ibm.ent.box.com/services/box_for_office_online/4881/544324563005/c277d8.589ce05350e115119c0f5d371f5a27545040cfd8caea26057557f925a160a73d?node_type=file

**Comment by jimpistilli** [comment]
@JennySanchez @jacobottesen-dgc Hey that's not the final content or Word doc. As the comment says above and discussed with @jeffchew, I need to see the numbers being included above written on the site to finish.  Also the Box link is not working, it is at:  

bm.box.com/s/254eglkvm8rww1qvu4gcqm8wi72mfqi2

**Comment by jacobottesen-dgc** [comment]
@jimpistilli Jeff told me that we can remove 1 & 4 for now. He also said "action logger will probably come back eventually but not show info."

**Comment by jimpistilli** [comment]
@jacobottesen-dgc OK but I still need to see the ones that aren't being removed. You told me about 5 already, but need to see 2. and 3 if they are remaining.

But it's not final, either way. cc: @JennySanchez

**Comment by jacobottesen-dgc** [comment]
![Screen Shot 2019-10-23 at 2.28.25 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/ffdca934-4b13-4027-b154-d90beb3f5dd5)

@jimpistilli Here is the screenshot

**Comment by JennySanchez** [comment]
@jacobottesen-dgc and @jimpistilli I love the collaboration going on here!
ps: Jacob, I have a few questions and let's take a look at this page together tomorrow.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc If the content and design are ready for the review on Monday. Please save the latest work file on [BOX folder](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg) and move this issue to "Review". Thank you.

**Comment by jacobottesen-dgc** [comment]
Design ready for review

![Coding.jpg](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/b7dd1f2e-a5a3-4a65-bb4e-07d4a4019ec6)

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you make sure the file is saved in the `Cupcake Website folder` then share the link here? Thanks.
