### ISSUE TITLE
Monthly Metrics - October

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#522]
_Benjamin-Hansen1 created the following on Oct 10:_  

 ## User story
As an IBMer interested in achieving successful NPS and CSAT levels, I need to see a monthly dashboard reporting current and ongoing statistics and user feedback, so I can plan for and/or encourage ongoing improvement.

## Deliverables
- [ ] Monthly report - https://lux.w3ibm.mybluemix.net/library/research/374/

## Acceptance Criteria
- [ ] Report completed, published, and shared with team
- [ ] The issue to create the metrics for the following month is created
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1825_

**Comment by JennySanchez** [comment]
Based on the conversation I had with Wonil, I will own this work and provide updates to the team.
FYI - @RobertaJHahn

**Comment by JennySanchez** [comment]
Based on the discussion with Wonil and James, we will no longer track the metric for the v19a website from this point on since we will no longer support changes to the v19a website. The only thing we will keep tracking with be the NPS score. Wonil discussed with Linda, and have Linda's thumbs up on the decision. 

ps: Task issue [21](https://github.com/carbon-design-system/carbon-for-ibm-website/issues/21) is set up for tracking the Cupcake Website. 

**For October, the NPS score is 43.**
![Screen Shot 2019-11-01 at 9.28.34 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c93eab01-9a7a-4bd8-b3a8-685579f1e73b)
