### ISSUE TITLE
Separate global imports into different package 

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#527]
When Drupal Team trying to pull the individual components or Patterns, The fonts css, globals imports css are getting duplicated which makes page performance slow which needs to pull the fonts from external source. If we can have the global import Separated from patterns/components and load only once as external that will help us to improve the performance and no duplicate css in the code.

**Comment by jeffchew** [comment]
@kennylam and I spoke with the DPP Pilot team, the issue here is that generated global styles (namely font declarations) are being included on the component level CSS. We have discussed separating out the CSS to have a global include, then have a separate include for the component level to have all necessary mixins/functions/etc for the component CSS to generate correctly without the generated global CSS in tow. 

cc: fireline support team: @photodow @JennySanchez

**Comment by photodow** [comment]
@jeffchew @sridharmula is there any code we can look at? Maybe a codesandbox with a reduced test case or something?

**Comment by ljcarot** [comment]
@jeffchew this story is closed. What Release was it delivered in?

**Comment by jeffchew** [comment]
> @jeffchew this story is closed. What Release was it delivered in?

I traced the commits, it was merged in mid November so this will be making v1.2.0. I have added the release to the ticket.
