### ISSUE TITLE
Create the lightbox functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#572]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have lightbox functional specs 

> so that I can:
so that I can properly code the lightbox component

#### Additional information

 - [Component: lightbox (image viewer) UX design #495](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/495)
 - [Component: lightbox (image viewer) final design #325](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/325)

#### Acceptance criteria
 - [ ] Documented functional lightbox specifications

**Comment by RobertaJHahn** [comment]
@photodow Is this work finished?  Can I close it in this sprint or move to Sprint 22?

**Comment by photodow** [comment]
@RobertaJHahn yeah, this is finished. Here is the temporary location. Sounds like we'll be moving it to Box, but the specs are done based on what we know right now.

https://github.com/photodow/ibm-dotcom-library/wiki/%5Bfs%5D-Media-Viewer

**Comment by jeffchew** [comment]
Consolidating feedback from slack conversations:

- need a section of links to other documentation, like the sketch file, storybook link (when completed). We should have a section for that here once we move this document to box.
- versioning of the documentation (we are talking about doing pre-release versions since these are still behind a feature flag, e.g. v0.1, v0.2 until we remove the feature flag and becomes v1.0)
- Should avoid React code in the documentation, we shouldn't be doing technical solutioning in this document, and should be framework agnostic
