### ISSUE TITLE
Understand the Brand and Media Center video discovery work

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#646]
#### User Story

> As a `[user role below]`:
DDS designer and developer

> I need to:
understand the video discovery work done by both the Brand and MediaCenter squads

> so that I can:
learn from their work and potentially include their learning in the DDS developed solution

#### Additional information

 - Jerry Ringuette:  MediaCenter Offering Manager
 - Russell Wakelin:  Brand Strategy and Experience Design Program Manager

#### Acceptance criteria
 - [ ] Meetings scheduled for information sharing

**Comment by wonilsuhibm** [comment]
### questions from WS team:
- what are the elements that an author needs to provide in order to successfully use videos?
- What are the capabilities of Kaltura platform
   - Eg) Title? any meta data? poster image? what are options? transcript?

@RobertaJHahn We should include Irene, Jill, Lila, Alain, Ke since WS will be the first adopter of this thing.

**Comment by RobertaJHahn** [comment]
Meeting scheduled Jan 8, 2020.  Follow-on work (issues) will be added to the [Video Play Design Epic #724]  (https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/724)
