### ISSUE TITLE
[Masthead] Styles overwritten by carbon bx--header depending on order of CSS loaded

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#673]
## Detailed description

> Describe in detail the issue you're having.

If `carbon-components.min.css` is included after the masthead scss, the header's background colors get overwritten by the standard carbon styles and makes it dark.

<img width="1552" alt="Screen Shot 2019-11-12 at 3 34 04 PM" src="https://user-images.githubusercontent.com/1641214/68708704-3e659500-0562-11ea-882f-eded3ba097cf.png">

**Comment by RobertaJHahn** [comment]
@jeffchew Is this a show stopper for the Web Simplification Learn page template?

**Comment by RobertaJHahn** [comment]
@kennylam Does the fix in (#1604) fix this issue?

**Comment by kennylam** [comment]
@RobertaJHahn No, that was a separate issue. I suggest closing this issue since it is the correct behavior. If Carbon's styles are loaded after ours, this is what we would expect to see. If a user/adopter is seeing this, it means that they are loading the css in the incorrect order, not to mention the fact that we don't support loading styles all at once, as is seen in the example.

**Comment by RobertaJHahn** [comment]
An issue to update the documentation will be recreated.  This issue will be referenced and closed.

**Comment by RobertaJHahn** [comment]
Issue (#1946) was created to update the documentation.  Closing this issue.
