### ISSUE TITLE
[Pictogram Array] Need to fix spacing

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#833]
## Detailed description

I'm creating this more as a placeholder. There are issues with the PictogramArray spacing (as I'll list below), but I believe most if not all of these will be solved if this pattern adopts the ContentArrayGroup #745.

- md title margin-top is wrong
- missing width and max-width on typography
- sm first item should only have 32px margin top

## Additional information

- [Design specs](https://ibm.box.com/s/iyrjxcp1lwymla8891hgsyl8bl4m0fvn)

**Comment by RobertaJHahn** [comment]
Moving this issue to the Icebox pipeline as the information may or may not be needed if the issue is resolved by adopting the Content Group Array.  This issue is referenced in [Issue 745 Content Array Group](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/745)

**Comment by ljcarot** [comment]
@photodow Do you want to let this issue close?  It looks like a placeholder and had a dependency on subpattern and refactoring work.  If you think it can be closed, please close. Thanks

**Comment by photodow** [comment]
I was looking at it and wondering the same thing. I think with the pattern ontology refactor we should be getting it done between that and all of the QA processes in place.
