### ISSUE TITLE
[Masthead] search functional specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#887]
#### User Story
> As a `[user role below]`:
IBM.com Library developer

> I need to:
be able to reference the masthead's search behavior

> so that I can:
confidently execute on my stories, and support in the future

#### Additional information
 - [Masthead navigation design folder](https://ibm.box.com/s/mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)

#### Acceptance criteria
- [ ] functional specs created and shared
- [ ] web simplification team approval
- [ ] design and development agreement
- [ ] stories (if necessary) to iterate and create

**Comment by photodow** [comment]
not stale

**Comment by ellenchoi1** [comment]
Func specs completed and links to specs added to epic: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1464

**Comment by RobertaJHahn** [comment]
There are some gaps between the functional specs and developed component.  Lara will be working on the design specs in sprint 20-12.  Ellen will transition her work to James so that both the design and functional specs can be used by the Prod QA testing team for their functional and cross browser testing.
