### ISSUE TITLE
Review Tags

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#929]
Review and document what needs to be updated in the themed components so that the developers can match the coded component to design intent.

**Acceptance criteria**
- [ ] issue created for developer

**Comment by oliviaflory** [comment]
I did a quick study of various heights and padding for the tag component, I think we might need to break away from the mini unit for height because 24px looks just a _tad_ squishy with the 14px font (though Carbon does this for inline components), and 32px looks quite fat.

I included the Carbon tag for reference which is 24px tall, 8px padding and 12px type.

I explored 
- 8, 10 and 12px padding 
- 24, 26, 28 and 32px height
- 14px type (because it's using the label size)

<img width="506" alt="Screen Shot 2020-01-13 at 6 07 22 PM" src="https://user-images.githubusercontent.com/45692622/72299843-0ba64e80-3630-11ea-8704-96aa9acc3640.png">


Would love to hear everyones thoughts on the different sizes if you have a moment 
@wonilsuhibm @larahanlon2 @JennySanchez @jacobottesen-dgc

**Comment by larahanlon2** [comment]
@oliviaflory I could see any other three 3 being most successful:

- `10px padding + 28px height` – proportionally, it looks the closest to Carbon, IMO.
- `12px padding + 26px height` – the text is slightly less prominent because of the extra padding, so it looks like the text is sitting more comfortably inside the bubble.
- `12px padding + 28px height` –  there's something nice about the additional space, especially when the close icon is active.

**Comment by JennySanchez** [comment]
@oliviaflory 

**For padding:**
8px padding is too tight visually and12px padding works the best.

**For height:**
I like the 28px height the best since 26px looks still tight and 32px looks too loose.

**Food for thought:**
Before you make the final decision, I'd also recommend putting the tags in a group or a UI mockup. By placing a few of them together or nearby components on a UI, it will also help with the decision making as well.

---

**FYI:**
There is a badge and tag shape-related happened yesterday on the Carbon Slack. In case you are not aware of the change, view the conversation thread [here](https://cognitive-app.slack.com/archives/GDAQ34WBB/p1578950499010500).

**Comment by oliviaflory** [comment]
After reviewing with the Carbon team, and confirming with Anna that the tag is utilizing `$spacing-03` to define the left and right padding, we will wait to decide on setting the height until we review the padding / margins in the next round.

One option could be to remove the use of `$spacing-03` in order to achieve the desired effect.
